# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from . import utilities, tables

class AdminGroup(pulumi.CustomResource):
    access_methods: pulumi.Output[list]
    comment: pulumi.Output[str]
    disable: pulumi.Output[bool]
    email_addresses: pulumi.Output[list]
    name: pulumi.Output[str]
    roles: pulumi.Output[list]
    superuser: pulumi.Output[bool]
    def __init__(__self__, resource_name, opts=None, access_methods=None, comment=None, disable=None, email_addresses=None, name=None, roles=None, superuser=None, __name__=None, __opts__=None):
        """
        Create a AdminGroup resource with the given unique name, props, and options.
        
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if not resource_name:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(resource_name, str):
            raise TypeError('Expected resource name to be a string')
        if opts and not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        __props__['access_methods'] = access_methods

        __props__['comment'] = comment

        __props__['disable'] = disable

        __props__['email_addresses'] = email_addresses

        __props__['name'] = name

        __props__['roles'] = roles

        __props__['superuser'] = superuser

        super(AdminGroup, __self__).__init__(
            'infoblox:index/adminGroup:AdminGroup',
            resource_name,
            __props__,
            opts)


    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

