# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from . import utilities, tables

class MXRecord(pulumi.CustomResource):
    comment: pulumi.Output[str]
    ddns_principal: pulumi.Output[str]
    ddns_protected: pulumi.Output[bool]
    disable: pulumi.Output[bool]
    mail_exchanger: pulumi.Output[str]
    name: pulumi.Output[str]
    preference: pulumi.Output[float]
    ttl: pulumi.Output[float]
    use_ttl: pulumi.Output[bool]
    view: pulumi.Output[str]
    def __init__(__self__, resource_name, opts=None, comment=None, ddns_principal=None, ddns_protected=None, disable=None, mail_exchanger=None, name=None, preference=None, ttl=None, use_ttl=None, view=None, __name__=None, __opts__=None):
        """
        Create a MXRecord resource with the given unique name, props, and options.
        
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if not resource_name:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(resource_name, str):
            raise TypeError('Expected resource name to be a string')
        if opts and not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        __props__['comment'] = comment

        __props__['ddns_principal'] = ddns_principal

        __props__['ddns_protected'] = ddns_protected

        __props__['disable'] = disable

        if mail_exchanger is None:
            raise TypeError("Missing required property 'mail_exchanger'")
        __props__['mail_exchanger'] = mail_exchanger

        __props__['name'] = name

        if preference is None:
            raise TypeError("Missing required property 'preference'")
        __props__['preference'] = preference

        __props__['ttl'] = ttl

        __props__['use_ttl'] = use_ttl

        __props__['view'] = view

        super(MXRecord, __self__).__init__(
            'infoblox:index/mXRecord:MXRecord',
            resource_name,
            __props__,
            opts)


    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

