# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from . import utilities, tables

class NSRecord(pulumi.CustomResource):
    addresses: pulumi.Output[list]
    creator: pulumi.Output[str]
    dns_name: pulumi.Output[str]
    ms_delegation_name: pulumi.Output[str]
    name: pulumi.Output[str]
    nameserver: pulumi.Output[str]
    policy: pulumi.Output[str]
    view: pulumi.Output[str]
    zone: pulumi.Output[str]
    def __init__(__self__, resource_name, opts=None, addresses=None, creator=None, dns_name=None, ms_delegation_name=None, name=None, nameserver=None, policy=None, view=None, __name__=None, __opts__=None):
        """
        Create a NSRecord resource with the given unique name, props, and options.
        
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if not resource_name:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(resource_name, str):
            raise TypeError('Expected resource name to be a string')
        if opts and not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        if addresses is None:
            raise TypeError("Missing required property 'addresses'")
        __props__['addresses'] = addresses

        __props__['creator'] = creator

        __props__['dns_name'] = dns_name

        __props__['ms_delegation_name'] = ms_delegation_name

        __props__['name'] = name

        if nameserver is None:
            raise TypeError("Missing required property 'nameserver'")
        __props__['nameserver'] = nameserver

        __props__['policy'] = policy

        __props__['view'] = view

        __props__['zone'] = None

        super(NSRecord, __self__).__init__(
            'infoblox:index/nSRecord:NSRecord',
            resource_name,
            __props__,
            opts)


    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

