# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from .. import utilities, tables

__config__ = pulumi.Config('infoblox')

allow_unverified_ssl = __config__.get('allowUnverifiedSsl') or utilities.get_env_bool('INFOBLOX_ALLOW_UNVERIFIED_SSL')
"""
If set, Infoblox client will permit unverifiable SSL certificates.
"""

client_debug = __config__.get('clientDebug') or utilities.get_env_bool('INFOBLOX_CLIENT_DEBUG')
"""
infoblox client debug
"""

password = utilities.require_with_default(lambda: __config__.require('password'), utilities.get_env('INFOBLOX_PASSWORD'))
"""
Password to authenticate with Infoblox appliance
"""

server = utilities.require_with_default(lambda: __config__.require('server'), utilities.get_env('INFOBLOX_SERVER'))
"""
Infoblox appliance to connect to eg https://192.168.0.1
"""

timeout = __config__.get('timeout') or utilities.get_env_int('INFOBLOX_CLIENT_TIMEOUT')
"""
http response timeout, in seconds
"""

username = utilities.require_with_default(lambda: __config__.require('username'), utilities.get_env('INFOBLOX_USERNAME'))
"""
User to authenticate with Infoblox appliance
"""

wapi_version = __config__.get('wapiVersion') or utilities.get_env('INFOBLOX_WAPI_VERSION')
"""
Infoblox WAPI server version, defaults to v2.6.1
"""

