// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package infoblox

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type NSGroupForwardStub struct {
	s *pulumi.ResourceState
}

// NewNSGroupForwardStub registers a new resource with the given unique name, arguments, and options.
func NewNSGroupForwardStub(ctx *pulumi.Context,
	name string, args *NSGroupForwardStubArgs, opts ...pulumi.ResourceOpt) (*NSGroupForwardStub, error) {
	if args == nil || args.ExternalServers == nil {
		return nil, errors.New("missing required argument 'ExternalServers'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["comment"] = nil
		inputs["externalServers"] = nil
		inputs["name"] = nil
	} else {
		inputs["comment"] = args.Comment
		inputs["externalServers"] = args.ExternalServers
		inputs["name"] = args.Name
	}
	s, err := ctx.RegisterResource("infoblox:index/nSGroupForwardStub:NSGroupForwardStub", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &NSGroupForwardStub{s: s}, nil
}

// GetNSGroupForwardStub gets an existing NSGroupForwardStub resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNSGroupForwardStub(ctx *pulumi.Context,
	name string, id pulumi.ID, state *NSGroupForwardStubState, opts ...pulumi.ResourceOpt) (*NSGroupForwardStub, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["comment"] = state.Comment
		inputs["externalServers"] = state.ExternalServers
		inputs["name"] = state.Name
	}
	s, err := ctx.ReadResource("infoblox:index/nSGroupForwardStub:NSGroupForwardStub", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &NSGroupForwardStub{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *NSGroupForwardStub) URN() *pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *NSGroupForwardStub) ID() *pulumi.IDOutput {
	return r.s.ID()
}

// Comment field
func (r *NSGroupForwardStub) Comment() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["comment"])
}

// The primary preference set with Grid member names and/or External Server structs for this member.
func (r *NSGroupForwardStub) ExternalServers() *pulumi.ArrayOutput {
	return (*pulumi.ArrayOutput)(r.s.State["externalServers"])
}

// The name of the name server group
func (r *NSGroupForwardStub) Name() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["name"])
}

// Input properties used for looking up and filtering NSGroupForwardStub resources.
type NSGroupForwardStubState struct {
	// Comment field
	Comment interface{}
	// The primary preference set with Grid member names and/or External Server structs for this member.
	ExternalServers interface{}
	// The name of the name server group
	Name interface{}
}

// The set of arguments for constructing a NSGroupForwardStub resource.
type NSGroupForwardStubArgs struct {
	// Comment field
	Comment interface{}
	// The primary preference set with Grid member names and/or External Server structs for this member.
	ExternalServers interface{}
	// The name of the name server group
	Name interface{}
}
