// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

let __config = new pulumi.Config("infoblox");

/**
 * If set, Infoblox client will permit unverifiable SSL certificates.
 */
export let allowUnverifiedSsl: boolean | undefined = __config.getObject<boolean>("allowUnverifiedSsl") || utilities.getEnvBoolean("INFOBLOX_ALLOW_UNVERIFIED_SSL");
/**
 * infoblox client debug
 */
export let clientDebug: boolean | undefined = __config.getObject<boolean>("clientDebug") || utilities.getEnvBoolean("INFOBLOX_CLIENT_DEBUG");
/**
 * Password to authenticate with Infoblox appliance
 */
export let password: string = utilities.requireWithDefault(() => __config.require("password"), utilities.getEnv("INFOBLOX_PASSWORD"));
/**
 * Infoblox appliance to connect to eg https://192.168.0.1
 */
export let server: string = utilities.requireWithDefault(() => __config.require("server"), utilities.getEnv("INFOBLOX_SERVER"));
/**
 * http response timeout, in seconds
 */
export let timeout: number | undefined = __config.getObject<number>("timeout") || utilities.getEnvNumber("INFOBLOX_CLIENT_TIMEOUT");
/**
 * User to authenticate with Infoblox appliance
 */
export let username: string = utilities.requireWithDefault(() => __config.require("username"), utilities.getEnv("INFOBLOX_USERNAME"));
/**
 * Infoblox WAPI server version, defaults to v2.6.1
 */
export let wapiVersion: string | undefined = __config.get("wapiVersion") || utilities.getEnv("INFOBLOX_WAPI_VERSION");
