// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AdminRole extends pulumi.CustomResource {
    /**
     * Get an existing AdminRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AdminRoleState, opts?: pulumi.CustomResourceOptions): AdminRole {
        return new AdminRole(name, <any>state, { ...opts, id: id });
    }

    /**
     * The descriptive comment of the Admin Role object.
     */
    public readonly comment: pulumi.Output<string | undefined>;
    public readonly disable: pulumi.Output<boolean | undefined>;
    /**
     * The name of an admin role.
     */
    public readonly name: pulumi.Output<string>;

    /**
     * Create a AdminRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AdminRoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AdminRoleArgs | AdminRoleState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: AdminRoleState = argsOrState as AdminRoleState | undefined;
            inputs["comment"] = state ? state.comment : undefined;
            inputs["disable"] = state ? state.disable : undefined;
            inputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as AdminRoleArgs | undefined;
            inputs["comment"] = args ? args.comment : undefined;
            inputs["disable"] = args ? args.disable : undefined;
            inputs["name"] = args ? args.name : undefined;
        }
        super("infoblox:index/adminRole:AdminRole", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AdminRole resources.
 */
export interface AdminRoleState {
    /**
     * The descriptive comment of the Admin Role object.
     */
    readonly comment?: pulumi.Input<string>;
    readonly disable?: pulumi.Input<boolean>;
    /**
     * The name of an admin role.
     */
    readonly name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AdminRole resource.
 */
export interface AdminRoleArgs {
    /**
     * The descriptive comment of the Admin Role object.
     */
    readonly comment?: pulumi.Input<string>;
    readonly disable?: pulumi.Input<boolean>;
    /**
     * The name of an admin role.
     */
    readonly name?: pulumi.Input<string>;
}
