// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export members:
export * from "./aRecord";
export * from "./adminGroup";
export * from "./adminRole";
export * from "./adminUser";
export * from "./cNameRecord";
export * from "./dHCPRange";
export * from "./dNSView";
export * from "./mXRecord";
export * from "./nSGroupDelegation";
export * from "./nSGroupForward";
export * from "./nSGroupForwardStub";
export * from "./nSGroupStub";
export * from "./nSRecord";
export * from "./network";
export * from "./permission";
export * from "./provider";
export * from "./sRVRecord";
export * from "./tXTRecord";
export * from "./zoneAuth";
export * from "./zoneDelegated";
export * from "./zoneForward";
export * from "./zoneStub";

// Export sub-modules:
import * as config from "./config/index";
export {config};
