// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class NSGroupForwardStub extends pulumi.CustomResource {
    /**
     * Get an existing NSGroupForwardStub resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NSGroupForwardStubState, opts?: pulumi.CustomResourceOptions): NSGroupForwardStub {
        return new NSGroupForwardStub(name, <any>state, { ...opts, id: id });
    }

    /**
     * Comment field
     */
    public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The primary preference set with Grid member names and/or External Server structs for this member.
     */
    public readonly externalServers: pulumi.Output<{ address: string, name: string, sharedWithMsParentDelegation: boolean, stealth?: boolean, tsigKey?: string, tsigKeyAlg?: string, tsigKeyName?: string, useTsigKeyName?: boolean }[]>;
    /**
     * The name of the name server group
     */
    public readonly name: pulumi.Output<string>;

    /**
     * Create a NSGroupForwardStub resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NSGroupForwardStubArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NSGroupForwardStubArgs | NSGroupForwardStubState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: NSGroupForwardStubState = argsOrState as NSGroupForwardStubState | undefined;
            inputs["comment"] = state ? state.comment : undefined;
            inputs["externalServers"] = state ? state.externalServers : undefined;
            inputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as NSGroupForwardStubArgs | undefined;
            if (!args || args.externalServers === undefined) {
                throw new Error("Missing required property 'externalServers'");
            }
            inputs["comment"] = args ? args.comment : undefined;
            inputs["externalServers"] = args ? args.externalServers : undefined;
            inputs["name"] = args ? args.name : undefined;
        }
        super("infoblox:index/nSGroupForwardStub:NSGroupForwardStub", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NSGroupForwardStub resources.
 */
export interface NSGroupForwardStubState {
    /**
     * Comment field
     */
    readonly comment?: pulumi.Input<string>;
    /**
     * The primary preference set with Grid member names and/or External Server structs for this member.
     */
    readonly externalServers?: pulumi.Input<pulumi.Input<{ address: pulumi.Input<string>, name: pulumi.Input<string>, sharedWithMsParentDelegation?: pulumi.Input<boolean>, stealth?: pulumi.Input<boolean>, tsigKey?: pulumi.Input<string>, tsigKeyAlg?: pulumi.Input<string>, tsigKeyName?: pulumi.Input<string>, useTsigKeyName?: pulumi.Input<boolean> }>[]>;
    /**
     * The name of the name server group
     */
    readonly name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a NSGroupForwardStub resource.
 */
export interface NSGroupForwardStubArgs {
    /**
     * Comment field
     */
    readonly comment?: pulumi.Input<string>;
    /**
     * The primary preference set with Grid member names and/or External Server structs for this member.
     */
    readonly externalServers: pulumi.Input<pulumi.Input<{ address: pulumi.Input<string>, name: pulumi.Input<string>, sharedWithMsParentDelegation?: pulumi.Input<boolean>, stealth?: pulumi.Input<boolean>, tsigKey?: pulumi.Input<string>, tsigKeyAlg?: pulumi.Input<string>, tsigKeyName?: pulumi.Input<string>, useTsigKeyName?: pulumi.Input<boolean> }>[]>;
    /**
     * The name of the name server group
     */
    readonly name?: pulumi.Input<string>;
}
