// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class NSGroupForward extends pulumi.CustomResource {
    /**
     * Get an existing NSGroupForward resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NSGroupForwardState, opts?: pulumi.CustomResourceOptions): NSGroupForward {
        return new NSGroupForward(name, <any>state, { ...opts, id: id });
    }

    /**
     * Comment field
     */
    public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The primary preference list with Grid member names and/or External Server structs for this member.
     */
    public readonly forwardingServers: pulumi.Output<{ forwardTos?: { address: string, name: string, sharedWithMsParentDelegation: boolean, stealth?: boolean, tsigKey?: string, tsigKeyAlg?: string, tsigKeyName?: string, useTsigKeyName?: boolean }[], forwardersOnly?: boolean, name: string, useOverrideForwarders?: boolean }[] | undefined>;
    /**
     * The name of the name server group
     */
    public readonly name: pulumi.Output<string>;

    /**
     * Create a NSGroupForward resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NSGroupForwardArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NSGroupForwardArgs | NSGroupForwardState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: NSGroupForwardState = argsOrState as NSGroupForwardState | undefined;
            inputs["comment"] = state ? state.comment : undefined;
            inputs["forwardingServers"] = state ? state.forwardingServers : undefined;
            inputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as NSGroupForwardArgs | undefined;
            inputs["comment"] = args ? args.comment : undefined;
            inputs["forwardingServers"] = args ? args.forwardingServers : undefined;
            inputs["name"] = args ? args.name : undefined;
        }
        super("infoblox:index/nSGroupForward:NSGroupForward", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NSGroupForward resources.
 */
export interface NSGroupForwardState {
    /**
     * Comment field
     */
    readonly comment?: pulumi.Input<string>;
    /**
     * The primary preference list with Grid member names and/or External Server structs for this member.
     */
    readonly forwardingServers?: pulumi.Input<pulumi.Input<{ forwardTos?: pulumi.Input<pulumi.Input<{ address: pulumi.Input<string>, name: pulumi.Input<string>, sharedWithMsParentDelegation?: pulumi.Input<boolean>, stealth?: pulumi.Input<boolean>, tsigKey?: pulumi.Input<string>, tsigKeyAlg?: pulumi.Input<string>, tsigKeyName?: pulumi.Input<string>, useTsigKeyName?: pulumi.Input<boolean> }>[]>, forwardersOnly?: pulumi.Input<boolean>, name: pulumi.Input<string>, useOverrideForwarders?: pulumi.Input<boolean> }>[]>;
    /**
     * The name of the name server group
     */
    readonly name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a NSGroupForward resource.
 */
export interface NSGroupForwardArgs {
    /**
     * Comment field
     */
    readonly comment?: pulumi.Input<string>;
    /**
     * The primary preference list with Grid member names and/or External Server structs for this member.
     */
    readonly forwardingServers?: pulumi.Input<pulumi.Input<{ forwardTos?: pulumi.Input<pulumi.Input<{ address: pulumi.Input<string>, name: pulumi.Input<string>, sharedWithMsParentDelegation?: pulumi.Input<boolean>, stealth?: pulumi.Input<boolean>, tsigKey?: pulumi.Input<string>, tsigKeyAlg?: pulumi.Input<string>, tsigKeyName?: pulumi.Input<string>, useTsigKeyName?: pulumi.Input<boolean> }>[]>, forwardersOnly?: pulumi.Input<boolean>, name: pulumi.Input<string>, useOverrideForwarders?: pulumi.Input<boolean> }>[]>;
    /**
     * The name of the name server group
     */
    readonly name?: pulumi.Input<string>;
}
