// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class NSGroupDelegation extends pulumi.CustomResource {
    /**
     * Get an existing NSGroupDelegation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NSGroupDelegationState, opts?: pulumi.CustomResourceOptions): NSGroupDelegation {
        return new NSGroupDelegation(name, <any>state, { ...opts, id: id });
    }

    /**
     * Comment field
     */
    public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The primary preference set with Grid member names and/or External Server structs for this member.
     */
    public readonly delegateTos: pulumi.Output<{ address: string, name: string, sharedWithMsParentDelegation: boolean, stealth?: boolean, tsigKey?: string, tsigKeyAlg?: string, tsigKeyName?: string, useTsigKeyName?: boolean }[]>;
    /**
     * The name of the name server group
     */
    public readonly name: pulumi.Output<string>;

    /**
     * Create a NSGroupDelegation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NSGroupDelegationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NSGroupDelegationArgs | NSGroupDelegationState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: NSGroupDelegationState = argsOrState as NSGroupDelegationState | undefined;
            inputs["comment"] = state ? state.comment : undefined;
            inputs["delegateTos"] = state ? state.delegateTos : undefined;
            inputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as NSGroupDelegationArgs | undefined;
            if (!args || args.delegateTos === undefined) {
                throw new Error("Missing required property 'delegateTos'");
            }
            inputs["comment"] = args ? args.comment : undefined;
            inputs["delegateTos"] = args ? args.delegateTos : undefined;
            inputs["name"] = args ? args.name : undefined;
        }
        super("infoblox:index/nSGroupDelegation:NSGroupDelegation", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NSGroupDelegation resources.
 */
export interface NSGroupDelegationState {
    /**
     * Comment field
     */
    readonly comment?: pulumi.Input<string>;
    /**
     * The primary preference set with Grid member names and/or External Server structs for this member.
     */
    readonly delegateTos?: pulumi.Input<pulumi.Input<{ address: pulumi.Input<string>, name: pulumi.Input<string>, sharedWithMsParentDelegation?: pulumi.Input<boolean>, stealth?: pulumi.Input<boolean>, tsigKey?: pulumi.Input<string>, tsigKeyAlg?: pulumi.Input<string>, tsigKeyName?: pulumi.Input<string>, useTsigKeyName?: pulumi.Input<boolean> }>[]>;
    /**
     * The name of the name server group
     */
    readonly name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a NSGroupDelegation resource.
 */
export interface NSGroupDelegationArgs {
    /**
     * Comment field
     */
    readonly comment?: pulumi.Input<string>;
    /**
     * The primary preference set with Grid member names and/or External Server structs for this member.
     */
    readonly delegateTos: pulumi.Input<pulumi.Input<{ address: pulumi.Input<string>, name: pulumi.Input<string>, sharedWithMsParentDelegation?: pulumi.Input<boolean>, stealth?: pulumi.Input<boolean>, tsigKey?: pulumi.Input<string>, tsigKeyAlg?: pulumi.Input<string>, tsigKeyName?: pulumi.Input<string>, useTsigKeyName?: pulumi.Input<boolean> }>[]>;
    /**
     * The name of the name server group
     */
    readonly name?: pulumi.Input<string>;
}
