// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class NSRecord extends pulumi.CustomResource {
    /**
     * Get an existing NSRecord resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NSRecordState, opts?: pulumi.CustomResourceOptions): NSRecord {
        return new NSRecord(name, <any>state, { ...opts, id: id });
    }

    /**
     * The list of zone name servers
     */
    public readonly addresses: pulumi.Output<{ address: string, autoCreatePtr?: boolean }[]>;
    /**
     * The record creator.Valid values:DYNAMIC,STATIC,SYSTEM.Defaults to STATIC
     */
    public readonly creator: pulumi.Output<string>;
    /**
     * The name for the NS record in punycode format. Values with leading or trailing white space are not valid for this
     * field. Cannot be written nor updated.
     */
    public readonly dnsName: pulumi.Output<string>;
    /**
     * The MS delegation point name
     */
    public readonly msDelegationName: pulumi.Output<string | undefined>;
    /**
     * The name of the ns record where the record should reside. Cannot be updated
     */
    public readonly name: pulumi.Output<string>;
    /**
     * The FQDN of the name server
     */
    public readonly nameserver: pulumi.Output<string>;
    public readonly policy: pulumi.Output<string>;
    /**
     * The name of the DNS view in which the record resides
     */
    public readonly view: pulumi.Output<string>;
    /**
     * DNS Zone for the record
     */
    public /*out*/ readonly zone: pulumi.Output<string>;

    /**
     * Create a NSRecord resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NSRecordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NSRecordArgs | NSRecordState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: NSRecordState = argsOrState as NSRecordState | undefined;
            inputs["addresses"] = state ? state.addresses : undefined;
            inputs["creator"] = state ? state.creator : undefined;
            inputs["dnsName"] = state ? state.dnsName : undefined;
            inputs["msDelegationName"] = state ? state.msDelegationName : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["nameserver"] = state ? state.nameserver : undefined;
            inputs["policy"] = state ? state.policy : undefined;
            inputs["view"] = state ? state.view : undefined;
            inputs["zone"] = state ? state.zone : undefined;
        } else {
            const args = argsOrState as NSRecordArgs | undefined;
            if (!args || args.addresses === undefined) {
                throw new Error("Missing required property 'addresses'");
            }
            if (!args || args.nameserver === undefined) {
                throw new Error("Missing required property 'nameserver'");
            }
            inputs["addresses"] = args ? args.addresses : undefined;
            inputs["creator"] = args ? args.creator : undefined;
            inputs["dnsName"] = args ? args.dnsName : undefined;
            inputs["msDelegationName"] = args ? args.msDelegationName : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["nameserver"] = args ? args.nameserver : undefined;
            inputs["policy"] = args ? args.policy : undefined;
            inputs["view"] = args ? args.view : undefined;
            inputs["zone"] = undefined /*out*/;
        }
        super("infoblox:index/nSRecord:NSRecord", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NSRecord resources.
 */
export interface NSRecordState {
    /**
     * The list of zone name servers
     */
    readonly addresses?: pulumi.Input<pulumi.Input<{ address: pulumi.Input<string>, autoCreatePtr?: pulumi.Input<boolean> }>[]>;
    /**
     * The record creator.Valid values:DYNAMIC,STATIC,SYSTEM.Defaults to STATIC
     */
    readonly creator?: pulumi.Input<string>;
    /**
     * The name for the NS record in punycode format. Values with leading or trailing white space are not valid for this
     * field. Cannot be written nor updated.
     */
    readonly dnsName?: pulumi.Input<string>;
    /**
     * The MS delegation point name
     */
    readonly msDelegationName?: pulumi.Input<string>;
    /**
     * The name of the ns record where the record should reside. Cannot be updated
     */
    readonly name?: pulumi.Input<string>;
    /**
     * The FQDN of the name server
     */
    readonly nameserver?: pulumi.Input<string>;
    readonly policy?: pulumi.Input<string>;
    /**
     * The name of the DNS view in which the record resides
     */
    readonly view?: pulumi.Input<string>;
    /**
     * DNS Zone for the record
     */
    readonly zone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a NSRecord resource.
 */
export interface NSRecordArgs {
    /**
     * The list of zone name servers
     */
    readonly addresses: pulumi.Input<pulumi.Input<{ address: pulumi.Input<string>, autoCreatePtr?: pulumi.Input<boolean> }>[]>;
    /**
     * The record creator.Valid values:DYNAMIC,STATIC,SYSTEM.Defaults to STATIC
     */
    readonly creator?: pulumi.Input<string>;
    /**
     * The name for the NS record in punycode format. Values with leading or trailing white space are not valid for this
     * field. Cannot be written nor updated.
     */
    readonly dnsName?: pulumi.Input<string>;
    /**
     * The MS delegation point name
     */
    readonly msDelegationName?: pulumi.Input<string>;
    /**
     * The name of the ns record where the record should reside. Cannot be updated
     */
    readonly name?: pulumi.Input<string>;
    /**
     * The FQDN of the name server
     */
    readonly nameserver: pulumi.Input<string>;
    readonly policy?: pulumi.Input<string>;
    /**
     * The name of the DNS view in which the record resides
     */
    readonly view?: pulumi.Input<string>;
}
