// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SRVRecord extends pulumi.CustomResource {
    /**
     * Get an existing SRVRecord resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SRVRecordState, opts?: pulumi.CustomResourceOptions): SRVRecord {
        return new SRVRecord(name, <any>state, { ...opts, id: id });
    }

    /**
     * Comment for the record; maximum 256 characters
     */
    public readonly comment: pulumi.Output<string | undefined>;
    /**
     * The name for a SRV record in FQDN format
     */
    public readonly name: pulumi.Output<string>;
    public readonly port: pulumi.Output<number>;
    public readonly priority: pulumi.Output<number>;
    public readonly target: pulumi.Output<string>;
    /**
     * The Time To Live assigned to CNAME
     */
    public readonly ttl: pulumi.Output<number | undefined>;
    public readonly useTtl: pulumi.Output<boolean>;
    /**
     * The name of the DNS View in which the record resides
     */
    public readonly view: pulumi.Output<string | undefined>;
    public readonly weight: pulumi.Output<number>;

    /**
     * Create a SRVRecord resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SRVRecordArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SRVRecordArgs | SRVRecordState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: SRVRecordState = argsOrState as SRVRecordState | undefined;
            inputs["comment"] = state ? state.comment : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["port"] = state ? state.port : undefined;
            inputs["priority"] = state ? state.priority : undefined;
            inputs["target"] = state ? state.target : undefined;
            inputs["ttl"] = state ? state.ttl : undefined;
            inputs["useTtl"] = state ? state.useTtl : undefined;
            inputs["view"] = state ? state.view : undefined;
            inputs["weight"] = state ? state.weight : undefined;
        } else {
            const args = argsOrState as SRVRecordArgs | undefined;
            if (!args || args.port === undefined) {
                throw new Error("Missing required property 'port'");
            }
            if (!args || args.priority === undefined) {
                throw new Error("Missing required property 'priority'");
            }
            if (!args || args.target === undefined) {
                throw new Error("Missing required property 'target'");
            }
            if (!args || args.weight === undefined) {
                throw new Error("Missing required property 'weight'");
            }
            inputs["comment"] = args ? args.comment : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["port"] = args ? args.port : undefined;
            inputs["priority"] = args ? args.priority : undefined;
            inputs["target"] = args ? args.target : undefined;
            inputs["ttl"] = args ? args.ttl : undefined;
            inputs["useTtl"] = args ? args.useTtl : undefined;
            inputs["view"] = args ? args.view : undefined;
            inputs["weight"] = args ? args.weight : undefined;
        }
        super("infoblox:index/sRVRecord:SRVRecord", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SRVRecord resources.
 */
export interface SRVRecordState {
    /**
     * Comment for the record; maximum 256 characters
     */
    readonly comment?: pulumi.Input<string>;
    /**
     * The name for a SRV record in FQDN format
     */
    readonly name?: pulumi.Input<string>;
    readonly port?: pulumi.Input<number>;
    readonly priority?: pulumi.Input<number>;
    readonly target?: pulumi.Input<string>;
    /**
     * The Time To Live assigned to CNAME
     */
    readonly ttl?: pulumi.Input<number>;
    readonly useTtl?: pulumi.Input<boolean>;
    /**
     * The name of the DNS View in which the record resides
     */
    readonly view?: pulumi.Input<string>;
    readonly weight?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a SRVRecord resource.
 */
export interface SRVRecordArgs {
    /**
     * Comment for the record; maximum 256 characters
     */
    readonly comment?: pulumi.Input<string>;
    /**
     * The name for a SRV record in FQDN format
     */
    readonly name?: pulumi.Input<string>;
    readonly port: pulumi.Input<number>;
    readonly priority: pulumi.Input<number>;
    readonly target: pulumi.Input<string>;
    /**
     * The Time To Live assigned to CNAME
     */
    readonly ttl?: pulumi.Input<number>;
    readonly useTtl?: pulumi.Input<boolean>;
    /**
     * The name of the DNS View in which the record resides
     */
    readonly view?: pulumi.Input<string>;
    readonly weight: pulumi.Input<number>;
}
